version: '3.8'

services:
  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: jruiz
      MYSQL_PASSWORD: password123
      MYSQL_DATABASE: mysql-db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - mysql-db
    environment:
      PMA_HOST: mysql-db
    ports:
      - "8081:80"

volumes:
  mysql-data:
    driver: local
